shahrul91/csileavemanagementsystem

- leavemanagement/package-lock.json
- leavemanagement/src/staffprofile/ChangePassword.js
Updated code. Please review and approve.
> updated change password page to have show password button

- leavemanagement/src/staffprofile/ChangePassword.js
> Change color of button for Show Password

- leavemanagement/src/common/Footer.js
- leavemanagement/src/common/Menu.js
- leavemanagement/src/hradmin/SideBar.js
- leavemanagement/src/hradmin/SideBarStyle.css
- leavemanagement/src/leaves/ApplyLeave.js
- leavemanagement/src/staffprofile/MyProfile.js
> Update footer receive dynamic year, add logout, sidebar menu

- leavemanagement/src/App.js
- leavemanagement/src/common/Footer.js
- leavemanagement/src/hradmin/SideBar.js
- leavemanagement/src/staffprofile/ListStaffProfile.js
> Fix issue footer and sidebar

- leavemanagement/src/home/Dashboard.js
- leavemanagement/src/home/HomePage.js
- leavemanagement/src/hradmin/SideBar.js
- leavemanagement/src/staffprofile/MyProfile.js
Approve pleaseeeeee. I update Dashboard.
> Fixmyprofile

- leavemanagement/src/App.js
- leavemanagement/src/hradmin/LeaveCategory.js
- leavemanagement/src/hradmin/PublicHoliday.js
- leavemanagement/src/hradmin/SideBar.js
> Add leave category page

- leavemanagement/src/common/Footer.js
- leavemanagement/src/home/HomePage.js
KIndly review and approve.
- Updated footer color to be same as Navbar color.
-Updated text shadow in jumbotron of homepage.
> Changefootercolor

- leavemanagement/src/staffprofile/MyProfile.js
- leavemanagement/src/staffprofile/NewStaffProfile.js
> add radio button, checkbox in newstaffprofile page

- leavemanagement/src/staffprofile/ListStaffProfile.js
> updated list staff profile page

- leavemanagement/src/hradmin/AddLeaveCategory.js
- leavemanagement/src/hradmin/AddPublicHoliday.js
- leavemanagement/src/hradmin/LeaveCategory.js
- leavemanagement/src/hradmin/PublicHoliday.js
- leavemanagement/src/leaves/AddNewLeave.js
- leavemanagement/src/leaves/ApplyLeave.js
- leavemanagement/src/leaves/LeaveEntitlement.js
- leavemanagement/src/leaves/MyLeaveDetails.js
- leavemanagement/src/leaves/MyLeaveHistory.js
- leavemanagement/src/staffprofile/ChangePassword.js
- leavemanagement/src/staffprofile/ListStaffProfile.js
- leavemanagement/src/staffprofile/MyProfile.js
- leavemanagement/src/staffprofile/NewStaffProfile.js
Please review and check. Updated all pages with title header.
> Update all pages with title header

- leavemanagement/src/common/Footer.js
- leavemanagement/src/common/Menu.js
- leavemanagement/src/home/Dashboard.js
- leavemanagement/src/hradmin/SideBar.js
> menu, footer, dashboard, sidebar bg color

- leavemanagement/src/common/Footer.js
- leavemanagement/src/common/Menu.js
- leavemanagement/src/hradmin/SideBar.js
> fixed footer, menu

- leavemanagement/src/common/Footer.js
- leavemanagement/src/hradmin/SideBar.js
> footer, sidebar

- src/main/java/com/csi/leavemanagement/models/StaffLeave.java
> Update leave details models and DB

- leavemanagement/src/home/HomePage.js
> Update homepage to fetch staff name

- leavemanagement/src/App.js
- leavemanagement/src/hradmin/AddPublicHoliday.js
- leavemanagement/src/hradmin/LeaveCategory.js
- leavemanagement/src/hradmin/PublicHoliday.js
- leavemanagement/src/leaves/EditEntitlement.js
- leavemanagement/src/leaves/LeaveEntitlement.js
- leavemanagement/src/staffprofile/ListStaffProfile.js
- leavemanagement/src/staffprofile/MyProfile.js
> edit leave entitlement to fetch the data from api

- leavemanagement/src/hradmin/LeaveCategory.js
- leavemanagement/src/hradmin/LeaveEntitlement.js
- leavemanagement/src/hradmin/PublicHoliday.js
- leavemanagement/src/hradmin/SideBar.js
- leavemanagement/src/hradmin/SideBarStyle.css
- leavemanagement/src/staffprofile/ListStaffProfile.js
- leavemanagement/src/staffprofile/NewStaffProfile.js
> hr layout 

- leavemanagement/src/test.html
please approve. this is testing only.
> this is just testing

- leavemanagement/src/App.js
- leavemanagement/src/hradmin/AddPublicHoliday.js
- leavemanagement/src/hradmin/EditEntitlement.js
- leavemanagement/src/hradmin/EditLeaveCategory.js
- leavemanagement/src/hradmin/EditPublicHoliday.js
- leavemanagement/src/hradmin/LeaveCategory.js
- leavemanagement/src/hradmin/LeaveEntitlement.js
- leavemanagement/src/hradmin/PublicHoliday.js
- leavemanagement/src/hradmin/SideBarStyle.css
- leavemanagement/src/staffprofile/ChangePassword.js
- leavemanagement/src/staffprofile/MyProfile.css
> hide/show pwd, added leave and public holiday pages

- leavemanagement/src/common/Styles.css
- leavemanagement/src/hradmin/AddLeaveCategory.js
- leavemanagement/src/hradmin/AddPublicHoliday.js
- leavemanagement/src/hradmin/EditEntitlement.js
- leavemanagement/src/hradmin/EditLeaveCategory.js
- leavemanagement/src/hradmin/EditPublicHoliday.js
- leavemanagement/src/hradmin/LeaveCategory.js
- leavemanagement/src/hradmin/LeaveEntitlement.js
- leavemanagement/src/hradmin/PublicHoliday.js
- leavemanagement/src/hradmin/SideBar.js
- leavemanagement/src/manager/ManagerApproval.js
- leavemanagement/src/manager/ManagerSideBar.js
- leavemanagement/src/manager/StaffLeaveHistory.js
- leavemanagement/src/staffprofile/ListStaffProfile.js
- leavemanagement/src/staffprofile/NewStaffProfile.js
> fixed hr & manager layout

- Client_CSILMS/src/App.js
- Client_CSILMS/src/common/Styles.css
- Client_CSILMS/src/hradmin/AddLeaveCategory.js
- Client_CSILMS/src/hradmin/AddPublicHoliday.js
- Client_CSILMS/src/hradmin/EditEntitlement.js
- Client_CSILMS/src/hradmin/EditLeaveCategory.js
- Client_CSILMS/src/hradmin/LeaveCategory.js
- Client_CSILMS/src/hradmin/LeaveEntitlement.js
- Client_CSILMS/src/hradmin/PublicHoliday.js
- Client_CSILMS/src/hradmin/SideBar.js
- Client_CSILMS/src/manager/ManagerApproval.js
- Client_CSILMS/src/manager/StaffLeaveHistory.js
- Client_CSILMS/src/staffprofile/ListStaffProfile.js
- Client_CSILMS/src/staffprofile/MyProfile.css
- Client_CSILMS/src/staffprofile/MyProfile.js
- Client_CSILMS/src/staffprofile/NewStaffProfile.js
- Client_CSILMS/src/staffprofile/ResetPassword.js
> hr & manager layout

- Client_CSILMS/src/leaves/MyLeaveDetails.js
- Client_CSILMS/src/leaves/MyLeaveHistory.js
- Client_CSILMS/src/staffprofile/MyProfile.css
> Jydevbranch

- Client_CSILMS/src/common/Styles.css
- Client_CSILMS/src/hradmin/AddLeaveCategory.js
- Client_CSILMS/src/hradmin/AddPublicHoliday.js
- Client_CSILMS/src/hradmin/EditEntitlement.js
- Client_CSILMS/src/hradmin/EditLeaveCategory.js
- Client_CSILMS/src/hradmin/EditPublicHoliday.js
- Client_CSILMS/src/hradmin/LeaveCategory.js
- Client_CSILMS/src/hradmin/LeaveEntitlement.js
- Client_CSILMS/src/hradmin/PublicHoliday.js
- Client_CSILMS/src/hradmin/SideBar.js
- Client_CSILMS/src/leaves/ApplyLeave.js
- Client_CSILMS/src/leaves/MyLeaveDetails.js
- Client_CSILMS/src/leaves/MyLeaveHistory.js
- Client_CSILMS/src/leaves/MyLeaveSummary.js
- Client_CSILMS/src/manager/ManagerApproval.js
- Client_CSILMS/src/manager/ManagerSideBar.js
- Client_CSILMS/src/manager/StaffLeaveHistory.js
- Client_CSILMS/src/staffprofile/ListStaffProfile.js
- Client_CSILMS/src/staffprofile/NewStaffProfile.js
- Client_CSILMS/src/staffprofile/ResetPassword.js
Changes are as follows:
-Removed all hard coded styles in each page, and put them all in Style.css.
-Standardized the looks and design of all modified pages.
Thanks!
> CSS/Styles Standardization

- Client_CSILMS/src/leaves/ApplyLeave.js
- Client_CSILMS/src/leaves/MyLeaveDetails.js
- Client_CSILMS/src/leaves/MyLeaveHistory.js
- Client_CSILMS/src/manager/ManagerApproval.js
- Client_CSILMS/src/manager/ManagerSideBar.js
- Client_CSILMS/src/manager/StaffLeaveHistory.js
- Client_CSILMS/src/staffprofile/MyProfile.css
- Client_CSILMS/src/staffprofile/MyProfile.js
> removed table's border

- Client_CSILMS/package-lock.json
- Client_CSILMS/package.json
- Client_CSILMS/src/common/history.js
- Client_CSILMS/src/leaves/ApplyLeave.js
> updated apply leave page

- Server_CSILMS/src/main/java/com/csi/leavemanagement/models/EmployeeDetails.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/models/LoginDetails.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/models/RoleName.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/models/Roles.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/repositories/EmployeeDetailsRepository.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/repositories/LoginDetailsRepository.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/repositories/RoleRepository.java
- Server_CSILMS/src/test/java/com/csi/leavemanagement/LeavemanagementApplicationTests.java
> Created JPA class for login, roles and employee details

- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/BusinessUnitRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/DepartmentRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/models/BusinessUnit.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/models/Department.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/repositories/AppliedLeaveRepository.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/repositories/BusinessUnitRepository.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/repositories/DepartmentRepository.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/services/BusinessUnitService.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/services/DepartmentService.java
- Fix missing Repository annotation in Applied Leave Repository
- Added new classes for Business Unit (only read methods in API and Service)
- Added new classes for Department (only read methods in API and Service)
> Chai back end model

- Client_CSILMS/src/App.js
- Client_CSILMS/src/staffprofile/ChangePassword.js
> changepassword page with eye/eye-slash icon

- Client_CSILMS/package-lock.json
- Client_CSILMS/package.json
- Client_CSILMS/src/common/Footer.js
- Client_CSILMS/src/common/Menu.js
- Client_CSILMS/src/common/Styles.css
- Client_CSILMS/src/hradmin/AddLeaveCategory.js
- Client_CSILMS/src/hradmin/AddPublicHoliday.js
- Client_CSILMS/src/hradmin/EditEntitlement.js
- Client_CSILMS/src/hradmin/EditLeaveCategory.js
- Client_CSILMS/src/hradmin/EditPublicHoliday.js
- Client_CSILMS/src/hradmin/LeaveCategory.js
- Client_CSILMS/src/hradmin/LeaveEntitlement.js
- Client_CSILMS/src/hradmin/PublicHoliday.js
- Client_CSILMS/src/leaves/ApplyLeave.js
- Client_CSILMS/src/staffprofile/ChangePassword.js
- Client_CSILMS/src/staffprofile/ListStaffProfile.js
- Client_CSILMS/src/staffprofile/NewStaffProfile.js
- Client_CSILMS/src/staffprofile/ResetPassword.js
> Removed unused objects and updated the button in all pages

- Client_CSILMS/src/common/Styles.css
- Client_CSILMS/src/home/Dashboard.js
- Client_CSILMS/src/staffprofile/MyProfile.js
-updated the View Profile page (Cards auto-arrange vertically in Mobile view)
-minor updates on Dashboard page and Styles.css (removed unused styles)
> Updated the View Profile and Dashboard pages

- Client_CSILMS/package-lock.json
- Client_CSILMS/src/App.js
- Client_CSILMS/src/common/Menu.js
- Client_CSILMS/src/common/SideBar.js
- Client_CSILMS/src/common/Styles.css
- Client_CSILMS/src/home/Dashboard.js
- Client_CSILMS/src/hradmin/AddPublicHoliday.js
- Client_CSILMS/src/hradmin/LeaveCategory.js
- Client_CSILMS/src/hradmin/LeaveEntitlement.js
- Client_CSILMS/src/hradmin/PublicHoliday.js
- Client_CSILMS/src/staffprofile/EditStaffProfile.js
- Client_CSILMS/src/staffprofile/ListStaffProfile.js
- Client_CSILMS/src/staffprofile/StaffTableRow.js
-Updated the Sidebar Links to change back color when Active
-Modified the Routing and Links of Add/Edit pages so the Sidebar Active Link don't lose it's track to the main Page.
> Updated the Sidebar Active Link and the Page Routing

- Client_CSILMS/src/staffprofile/ResetPassword.js
Updated reset password page with validation and show/hide password. Please approve.
> update reset password page with validation and show/hide password

- Client_CSILMS/src/staffprofile/EditStaffProfile.js
- Client_CSILMS/src/staffprofile/ListStaffProfile.js
- Client_CSILMS/src/staffprofile/NewStaffProfile.js
- Client_CSILMS/src/staffprofile/StaffTableRow.js
> removed reset password button from new staff page

- Server_CSILMS/.gitignore
- Server_CSILMS/src/main/resources/application.properties
- Commented all API to avoid error when running frontend
- Ignore application.properties file. Developer need to change database according to their preferences.
- Front end developer need to resolve bugs eg: hamburger sidebar menu issue.
> Fixdevelopment

- Client_CSILMS/src/leaves/ApplyLeave.js
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/LeaveEntitlementRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/models/AppliedLeave.java
- **ApplyLeave Java model** : update constructor and add getter setters for EmployeeDetails attributes (fetching appliedLeave from DB will also fetch corresponding employee details)
- **LeaveEntitlement Service** : added method to retrieve current user's leave entitlement
- **ApplyLeave.js (front end)** : retrieve AL Entitlement, Employee ID and Name, list of Leave Category from updated API
> Chai apply leave

- Client_CSILMS/src/leaves/ApplyLeave.js
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/EmployeeDetailsController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/models/EmployeeDetails.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/repositories/EmployeeDetailsRepository.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/services/EmployeeDetailsService.java
- **EmployeeDetails model** : added new attribute, Roles (Set). This Set contains the Employee's Roles ( **E**mployee, **M**anager, **H**R Admin)
- **EmployeeDetails Repository, Service, Controller** : added new method to retrieve all Managers, as leave approvers
- **ApplyLeave.js** : retrieve approver list from API
> Added Roles to EmployeeDetails, and function to retrieve Managers list

- Client_CSILMS/src/App.js
- Client_CSILMS/src/login/Login.css
- Client_CSILMS/src/login/Login.js
- Client_CSILMS/src/login/LoginError.js
Please review and approve.
Thanks!
> Updated the Login Page UI

- Client_CSILMS/src/leaves/MyLeaveDetails.js
- Completed my leave details page. Now can fetch data from API and load to the table.
> Myleavedetails

- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/AppliedLeaveRestController.java
- Update Applied Leave Controller to include localhost/api/appliedleave/me
please approve.
> Update Applied Leave Controller to include localhost/apiappliedleave/me

- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/AppliedLeaveRestController.java
Added method to AppliedLeave API - for retrieving leave requests for managers
> Chai applied leave api

- Client_CSILMS/src/test.html
> Test branch

- Client_CSILMS/src/home/HomePage.js
- display notification in homepage if manager pending to approve staff request.
> Managernotification

- Client_CSILMS/src/hradmin/LeaveCategory.js
- Client_CSILMS/src/hradmin/LeaveEntitlement.js
- Client_CSILMS/src/hradmin/PublicHoliday.js
- Client_CSILMS/src/staffprofile/ListStaffProfile.js
- Updated HR module to fetch data for view Leave Category, Leave Entitlement, Public Holiday & Employee Profile.
> Hrfetchdata

- Client_CSILMS/package-lock.json
- Client_CSILMS/package.json
- Client_CSILMS/src/hradmin/LeaveEntitlement.js
- Client_CSILMS/src/hradmin/LoginDetails.js
- Client_CSILMS/src/hradmin/PublicHoliday.js
- Client_CSILMS/src/leaves/MyLeaveHistory.js
- Client_CSILMS/src/staffprofile/ListStaffProfile.js
- Client_CSILMS/src/staffprofile/MyProfile.js
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/LoginDetailController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/models/LeaveEntitlement.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/repositories/LoginDetailsRepository.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/services/LoginDetailService.java
Updated Leave Entitlement to display name in the table as it missed out
Added Login Detail repository, service and controller
Install react-moment to format date and updated all date to use react-moment
Will approve myself.
> Shahruldev

- Client_CSILMS/src/manager/StaffLeaveHistory.js
> fetch data to Manage view Leave request page

- Client_CSILMS/package-lock.json
- Client_CSILMS/src/App.js
- Client_CSILMS/src/hradmin/EditEntitlement.js
- Client_CSILMS/src/hradmin/LeaveCategory.js
- Client_CSILMS/src/hradmin/LeaveEntitlement.js
- Client_CSILMS/src/hradmin/LoginDetails.js
- Client_CSILMS/src/hradmin/PublicHoliday.js
- Client_CSILMS/src/leaves/MyLeaveHistory.js
- Client_CSILMS/src/staffprofile/ListStaffProfile.js
> Fixed routing

- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/AppliedLeaveRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/services/AppliedLeaveService.java
Added server validation on Leave Status based on Translated Item from Database
> Add validation on leave status

- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/AppliedLeaveRestController.java
update message as per suggested
> Update PATCH successful ResponseEntity message

- Client_CSILMS/src/App.js
- Client_CSILMS/src/hradmin/EditPublicHoliday.js
- Client_CSILMS/src/hradmin/PublicHoliday.js
- Client_CSILMS/src/leaves/ApplyLeave.js
- Client_CSILMS/src/manager/LeaveRequest.js
- Client_CSILMS/src/manager/LeaveRequestsList.js
- Client_CSILMS/src/staffprofile/EditStaffProfile.js
- Client_CSILMS/src/staffprofile/ListStaffProfile.js
- Client_CSILMS/src/staffprofile/StaffProfilesToExcel.js
> Employee Profile

- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/EmployeeDetailsController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/repositories/EmployeeDetailsRepository.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/services/EmployeeDetailsService.java
Added new method to Employee API: lookup list of employees without Login Details (HR only)
> Chai new employee api

- Client_CSILMS/src/App.js
- Client_CSILMS/src/common/Styles.css
- Client_CSILMS/src/hradmin/AddLoginDetails.js
- Client_CSILMS/src/hradmin/LoginDetails.js
- Client_CSILMS/src/manager/LeaveHistory.js
- Client_CSILMS/src/manager/LeaveHistoryList.js
- Client_CSILMS/src/manager/LeaveHistoryToExcel.js
- Client_CSILMS/src/manager/LeaveHistoryView.js
- Client_CSILMS/src/manager/LeaveRequest.js
- Client_CSILMS/src/manager/LeaveRequestsList.js
- Client_CSILMS/src/manager/StaffLeaveHistory.js
- Client_CSILMS/src/staffprofile/ListStaffProfile.js
- Client_CSILMS/src/staffprofile/StaffProfilesToExcel.js
Updates covers the following:
> Leave Requests Listing and Approval/Rejection
> Leave History Listing, Vieiwing of each Leave Request, and Exporting to Excel
> Login Details Listing (Merged with Khairul's Reset Password functionality. Discussed and agreed with him that he will continue to work on this, to add Toggle Button for Locking/Unlocking of Account, he will also automatically create User Login Details upon creation and saving of New Employee)
Please review and approve.
Thanks!
> Leave Requests List and Approval,etc

- Client_CSILMS/src/App.js
- Client_CSILMS/src/hradmin/AddLeaveCategory.js
- Client_CSILMS/src/hradmin/AddPublicHoliday.js
- Client_CSILMS/src/hradmin/EditLeaveCategory.js
- Client_CSILMS/src/hradmin/LeaveCategory.js
- Client_CSILMS/src/hradmin/PublicHoliday.js
- Client_CSILMS/src/staffprofile/EditStaffProfile.js
> applied ReactTable to public holiday page

- Client_CSILMS/src/hradmin/AddLeaveCategory.js
- Client_CSILMS/src/hradmin/EditLeaveCategory.js
- Client_CSILMS/src/hradmin/LeaveCategory.js
- Client_CSILMS/src/staffprofile/EditStaffProfile.js
> completed leave category page (add-edit)

- Client_CSILMS/src/App.js
- Client_CSILMS/src/hradmin/EditEntitlement.js
- Client_CSILMS/src/hradmin/EditLeaveCategory.js
- Client_CSILMS/src/hradmin/LeaveEntitlement.js
> added delete function in leave category

- Client_CSILMS/src/hradmin/AddLeaveCategory.js
- Client_CSILMS/src/hradmin/AddPublicHoliday.js
- Client_CSILMS/src/hradmin/EditLeaveCategory.js
- Client_CSILMS/src/hradmin/EditPublicHoliday.js
- Client_CSILMS/src/hradmin/LeaveCategory.js
- Client_CSILMS/src/hradmin/PublicHoliday.js
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/PublicHolidayRestController.java
> completed public holiday page (add-edit)

- Client_CSILMS/src/leaves/ApplyLeave.js
- Client_CSILMS/src/util/APIUtils.js
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/AppliedLeaveRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/repositories/AppliedLeaveRepository.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/services/AppliedLeaveService.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/storage/FileSystemStorageService.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/storage/FileUploadController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/storage/StorageException.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/storage/StorageFileNotFoundException.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/storage/StorageProperties.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/storage/StorageService.java
- Create API to upload file
- Complete ApplyLeave attachment functionality
- Update /appliedleave/me/pendingapproval to also retrieve leaves pending cancellation
> Chai file upload

- Client_CSILMS/src/leaves/ApplyLeave.js
- Client_CSILMS/src/util/APIUtils.js
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/AppliedLeaveRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/LeaveEntitlementRestController.java
**ApplyLeave.js and APIUtils.js :** 
1. Rename the custom header property for better readability, 
2. Clean up the customer header property when creating new header (APIUtils.js)
3. Upload file only if user selected a file
4. Remove alerts (for debugging)
**Leave Entitlement API :** 
1. Update PATCH request mapping
2. Added bulk insert API (method = POST, URL = /leaveentitlement/bulk)
**Applied Leave API :** 
1. Update DELETE request mapping
> Chai update api

- Client_CSILMS/src/hradmin/EditPublicHoliday.js
- Client_CSILMS/src/leaves/ApplyLeave.js
> applied new ui to apply leave page

- Client_CSILMS/src/hradmin/LoginDetails.js
- Fixed user lock account display all as NO. Use number instead of string
> Fixed user lock account display all as NO. Use number instead of string

- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/AppliedLeaveRestController.java
Correct the notification message after the leave cancellation
> Fix defect: update return value upon successful Delete AppliedLeave

- Client_CSILMS/src/App.js
- Client_CSILMS/src/staffprofile/NewStaffProfile.js
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/EmployeeDetailsController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/models/EmployeeDetails.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/repositories/EmployeeDetailsRepository.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/services/EmployeeDetailsService.java
> Functionality - HR: Add New Employee

- Client_CSILMS/src/hradmin/LeaveCategoryToExcel.js
- Client_CSILMS/src/hradmin/LeaveEntitlementToExcel.js
- Client_CSILMS/src/hradmin/PublicHolidayToExcel.js
- Client_CSILMS/src/leaves/MyLeaveDetailsToExcel.js
- Client_CSILMS/src/leaves/MyLeaveHistoryToExcel.js
- Client_CSILMS/src/manager/LeaveHistoryToExcel.js
- Client_CSILMS/src/manager/LeaveRequestListToExcel.js
- Client_CSILMS/src/staffprofile/StaffProfilesToExcel.js
resolved error excel features. added index as a key
please approve
> resolved error excel features. added index as a key

- Client_CSILMS/src/App.js
- Client_CSILMS/src/common/FirstTime.js
- Client_CSILMS/src/common/PrivateRoute.js
- Client_CSILMS/src/constants/index.js
- Client_CSILMS/src/staffprofile/ChangePassword.js
- Client_CSILMS/src/staffprofile/NewStaffProfile.js
- Client_CSILMS/src/util/APIUtils.js
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/LoginDetailController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/services/LoginDetailService.java
Force to change password after the HR reset password or when the password is same as IC/Passport.
> Firsttime loginForce to change password after the HR reset password or when the password is same as IC/Passport.

- Client_CSILMS/src/login/Login.js
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/AuthController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/TranslateitemRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/repositories/LoginDetailsRepository.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/security/CustomUserDetailsService.java
Handling when user account is locked
> Handling when user account is locked

- Client_CSILMS/src/hradmin/LeaveEntitlement.js
- Client_CSILMS/src/staffprofile/MyProfile.js
- Client_CSILMS/src/staffprofile/NewStaffProfile.js
> changed CSI ID to Employee ID. Formatted Employee Profiles (add) page

- Client_CSILMS/src/leaves/MyLeaveHistoryView.js
- Client_CSILMS/src/manager/LeaveHistoryView.js
- Client_CSILMS/src/manager/LeaveRequest.js
- Client_CSILMS/src/util/APIUtils.js
- Added new fetchFile method in APIUtils to fetch non-JSON response without header
- Allow employee to view attachment from My Leave History
- Allow manager to view attachment from Manager Leave Requests and Manager Leave History
> Chai view attachment

- Client_CSILMS/src/hradmin/LoginDetails.js
- Client_CSILMS/src/login/Login.js
- Client_CSILMS/src/staffprofile/NewStaffProfile.js
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/LoginDetailController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/services/EmployeeDetailsService.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/services/LoginDetailService.java
1. Add lock/unlock account in logindetails page
2. When employee set inactive then login acc will lock automatically
> Add lock/unlock account in logindetails page

- Client_CSILMS/src/leaves/MyLeaveDetails.js
Made some change to ReactTable, kindly review.
> update myLeaveDetail-select only current year entitlement and resolve empty empty row when select more than 10 rows.

- Client_CSILMS/package-lock.json
- Client_CSILMS/src/leaves/MyLeaveHistoryView.js
Completed recall button changes and notification.
> Khairulashraf test

- Client_CSILMS/src/leaves/ApplyLeave.js
- Server_CSILMS/src/main/resources/application.properties
Server validation on file size perform thru configuration in application.properties
Also perform validation on Front End upon file selection
> Added file upload limit of 5MB

- Client_CSILMS/src/staffprofile/NewStaffProfile.js
- Server_CSILMS/.gitignore
- Server_CSILMS/src/main/java/com/csi/leavemanagement/config/SecurityConfig.java
- Server_CSILMS/src/main/java/logback-spring.xml
1) Added logging configuration file
2) Fix defect in edit employee profile where dotted line manager not
loaded
3) Fix security configuration to allow resources files load before
authorized
> Error Log - Configure to log errors messages from system

- Client_CSILMS/src/home/HomePage.js
> fix notification

- Client_CSILMS/src/leaves/ApplyLeave.js
Fix bug where system crash when user manually entered an invalid date while apply leave
> Chai bug apply leave date

- Client_CSILMS/src/App.js
- Client_CSILMS/src/common/PageHeader.js
- Client_CSILMS/src/common/PageSideBar.js
- Client_CSILMS/src/common/SideBarHeader.css
- Client_CSILMS/src/common/Styles.css
- Client_CSILMS/src/home/HomePage.js
- Client_CSILMS/src/hradmin/AddEntitlement.js
As default, upon Login, Sidebar is shown on Desktop view, but hidden on Mobile view.
Fixed issues related to the introduction of new SideBar.
> More SideBar Changes

- Client_CSILMS/src/leaves/ApplyLeave.js
Previous fix on apply leave date cause the checkbox for Half Day leave not working. Updated and fix the issue
> Fix bug on apply leave

- Client_CSILMS/src/staffprofile/ChangePassword.js
> fix eye icon

- Client_CSILMS/src/App.js
- Client_CSILMS/src/common/PageHeader.js
- Client_CSILMS/src/common/SideBarHeader.css
- Client_CSILMS/src/common/Styles.css
- Client_CSILMS/src/hradmin/PublicHoliday.js
- Client_CSILMS/src/login/Login.css
Issues fixed were as follows:
- Login button overlaps with other objects above it, upon keying UserID/Password;
-"<div />" text was visible on the Login page;
-Login page wasn't returning to Mobile view when logged out.
> Fixed issues on Login page on Mobile view

- Client_CSILMS/src/leaves/ApplyLeave.js
Update to fix mobile view of Apply Leave Page
> Fix apply leave mobile view

- Client_CSILMS/src/leaves/ApplyLeave.js
- Server_CSILMS/src/main/java/com/csi/leavemanagement/services/AppliedLeaveService.java
Issue #150 : error handling when Leave Entitlement is not available, return appropriate error message
> Bug #150 - Fix error message when Leave Entitlement not found

- Client_CSILMS/src/leaves/MyLeaveHistory.js
- Client_CSILMS/src/leaves/MyLeaveHistoryToExcel.js
- Client_CSILMS/src/leaves/MyLeaveHistoryView.js
- Client_CSILMS/src/manager/LeaveHistoryList.js
- Client_CSILMS/src/manager/LeaveRequest.js
- Client_CSILMS/src/manager/LeaveRequestsList.js
- Client_CSILMS/src/staffprofile/ListStaffProfile.js
> removed hardcoded fields

- Client_CSILMS/src/hradmin/EditTranslateItem.js
- Client_CSILMS/src/staffprofile/NewStaffProfile.js
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/EmployeeDetailsController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/repositories/EmployeeDetailsRepository.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/services/EmployeeDetailsService.java
- Fix issue #158 
- Added validation to check if any Employee is using the Translated Item before deactivating (inactive) it Business Unit / Department ID / Marriage Status / Gender.
> Chai bug158 inactive status

- Client_CSILMS/src/hradmin/EditLeaveCategory.js
- Client_CSILMS/src/hradmin/EditTranslateItem.js
- Removed Delete button from Edit Leave Category page
- Removed some Console Log on Edit Leave Category page
- Removed 1 unused code from Edit Translate Item page
> Chai bug160 delete leave category

- Client_CSILMS/src/manager/LeaveHistoryView.js
> removed hardcoded fields from LeaveHistoryView.js

- Client_CSILMS/package-lock.json
- Client_CSILMS/package.json
- Client_CSILMS/src/App.js
- Client_CSILMS/src/common/Styles.css
- Client_CSILMS/src/index.js
- Client_CSILMS/src/leaves/ApplyLeave.js
- Client_CSILMS/src/staffprofile/ChangePassword.js
- Client_CSILMS/src/staffprofile/MyProfile.js
-Apply Leave -> Updated the Leave Duration Computation based on Leave Types. The program will count all days within the Date Coverage if Leave Type is Maternity, Paternity, Medical Leave - Hospitalization or Medical Leave - Outpatient. Leave Duration Computation for the rest still the same which excludes Weekends and Holidays.
-Change Password -> Updated the user interface design, made it uniform to all pages design. It's design also able to adjust to any device sizes.
-My Profile -> Minor changes on this page.
> Updates on Apply Leave, Change Password, etc.

- Client_CSILMS/package-lock.json
- Client_CSILMS/package.json
- Client_CSILMS/src/leaves/ApplyLeave.js
- Client_CSILMS/src/test.html
- Client_CSILMS/src/util/APIUtils.js
In Reference to Issue #187 
Updated Apply Leave page to allow manual entries on Start and End Dates as IE 11 doesn't support DatePicker, updated the Leave Duration computation as some Date functions aren't supported as well.
> Fixed Internet Explorer 11 Compatibility Issue

- Client_CSILMS/src/leaves/ApplyLeave.js
- Client_CSILMS/src/leaves/MyLeaveHistory.js
- Client_CSILMS/src/leaves/MyLeaveHistoryView.js
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/AppliedLeaveRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/EmployeeDetailsController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/JobDetailRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/LeaveCategoryRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/LeaveDetailRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/LeaveEntitlementRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/LoginDetailController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/PersonDetailRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/PublicHolidayRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/StaffLeaveRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/StaffProfileRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/TranslateitemRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/services/AppliedLeaveService.java
- Added Authorization on HR and Manager functions
- Fix bug where cannot apply leave overlap with cancelled leave
- Removed several Console.Log
> Chai new secure api

- Client_CSILMS/src/hradmin/AddEntitlement.js
- Client_CSILMS/src/hradmin/AddPublicHoliday.js
- Client_CSILMS/src/hradmin/EditEntitlement.js
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/AppliedLeaveRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/LeaveEntitlementRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/repositories/AppliedLeaveRepository.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/services/AppliedLeaveService.java
Changes for #154  , #163 ,  #186 
- Add API method to calculate total leave applied and approved (Leave Taken)
- Leave Entitlement disable Input into Taken Leave and Balance Leave
- When add new Leave Entitlement, Taken Leave is set to 0, Balance Leave = Available Leave
- When edit existing Leave Entitlement, Taken Leave is validated against Calculated Leave from Applied Leave API, Balance Leave = Available Leave - Taken Leave
- Adjusted Leave Entitlement page layout, resize numeric fields, and added field for validation message
- Fix issue with Public Holiday react table not being refresh after adding new public holiday
> Chai 154and163 leave entitlement

- Client_CSILMS/src/hradmin/AddLeaveCategory.js
- Client_CSILMS/src/hradmin/AddPublicHoliday.js
- Client_CSILMS/src/hradmin/AddTranslateItem.js
Code fix at **front-end** for issue #204 (_**No duplicate check when adding new records**_).
HR will not be able to add duplicate items and changes are applied for:
- Add Leave Category
- Add Public Holiday
- Add Translate Item
> Ashraf FE TI PH LC check Dup

- Client_CSILMS/src/hradmin/EditPublicHoliday.js
Added dialog message to redirect to react table
> Handle missing data during fetch

- Client_CSILMS/src/hradmin/AddPublicHoliday.js
- Client_CSILMS/src/hradmin/EditPublicHoliday.js
Imposing text limit for **Description** (**`30`**) and **State** (**`100`**) fields for **Public Holiday** modules (Add/Edit).
> Ashraf PH Text Limit

- Client_CSILMS/src/App.js
- Client_CSILMS/src/common/PageSideBar.js
- Client_CSILMS/src/hradmin/LeaveHistoryHR.js
- Client_CSILMS/src/hradmin/LeaveHistoryViewHR.js
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/AppliedLeaveRestController.java
Duplicate the Manager Leave History into HR Module
> View all employee apllied leave for HR Module

- Client_CSILMS/public/index.html
- Client_CSILMS/src/hradmin/AddTranslateItem.js
- Client_CSILMS/src/hradmin/TranslateItems.js
- Client_CSILMS/src/index.js
-Changed FieldName Input Type from TextBox to ComboBox.
-Added real-time validation for the uniqueness of inputted FieldName and FieldValue combination.
> Add New Translate Item

- Client_CSILMS/.vscode/launch.json
- Client_CSILMS/src/App.js
- Client_CSILMS/src/common/PageSideBar.js
- Client_CSILMS/src/manager/LeaveEntitlementManager.js
- Server_CSILMS/src/main/java/com/csi/leavemanagement/controllers/LeaveEntitlementRestController.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/models/LeaveEntitlement.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/models/ReportingManager.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/repositories/LeaveEntitlementRepository.java
- Server_CSILMS/src/main/java/com/csi/leavemanagement/services/LeaveEntitlementService.java
Changes related to issue **#222** :
_"Allow Managers to view Leave Entitlements/Balances for those who report to them only."_
Additional link (**`Leave Entitlements`**) added in **Manager Dashboard**.
> Ashraf Add Entitlement for Manager (P2)
